In [189]:
import pandas as pd
from sklearn import datasets

linnerud = datasets.load_linnerud()
df = pd.DataFrame(linnerud.data, columns=linnerud.feature_names)

df.head(20)

    Chins  Situps  Jumps
0     5.0   162.0   60.0
1     2.0   110.0   60.0
2    12.0   101.0  101.0
3    12.0   105.0   37.0
4    13.0   155.0   58.0
5     4.0   101.0   42.0
6     8.0   101.0   38.0
7     6.0   125.0   40.0
8    15.0   200.0   40.0
9    17.0   251.0  250.0
10   17.0   120.0   38.0
11   13.0   210.0  115.0
12   14.0   215.0  105.0
13    1.0    50.0   50.0
14    6.0    70.0   31.0
15   12.0   210.0  120.0
16    4.0    60.0   25.0
17   11.0   230.0   80.0
18   15.0   225.0   73.0
19    2.0   110.0   43.0

In [190]:
df.isnull().sum()

Chins     0
Situps    0
Jumps     0
dtype: int64

In [191]:
features = linnerud.feature_names
label = linnerud.target_names

print("Özellikler (Features):", features)
print("Etiketler (Labels):", label)

Özellikler (Features): ['Chins', 'Situps', 'Jumps']
Etiketler (Labels): ['Weight', 'Waist', 'Pulse']

In [192]:
y_df = pd.DataFrame(linnerud.target, columns=linnerud.target_names)
full_df = pd.concat([df, y_df], axis=1)
full_df.head(10)

   Chins  Situps  Jumps  Weight  Waist  Pulse
0    5.0   162.0   60.0   191.0   36.0   50.0
1    2.0   110.0   60.0   189.0   37.0   52.0
2   12.0   101.0  101.0   193.0   38.0   58.0
3   12.0   105.0   37.0   162.0   35.0   62.0
4   13.0   155.0   58.0   189.0   35.0   46.0
5    4.0   101.0   42.0   182.0   36.0   56.0
6    8.0   101.0   38.0   211.0   38.0   56.0
7    6.0   125.0   40.0   167.0   34.0   60.0
8   15.0   200.0   40.0   176.0   31.0   74.0
9   17.0   251.0  250.0   154.0   33.0   56.0

In [193]:
from sklearn.model_selection import train_test_split

X, y = full_df[features].values, full_df[label].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape[0])
print("X_test shape:", X_test.shape[0])

X_train shape: 16
X_test shape: 4

In [194]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)

In [195]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, pred)
print("Mean Squared Error:", mse)
rmse = np.sqrt(mse)
print("Root Mean Squared Error:", rmse)
r2 = r2_score(y_test, pred)
print("R^2 Score:", r2)

Mean Squared Error: 239.15367187682764
Root Mean Squared Error: 15.464594138768325
R^2 Score: -1.3504115542086363

In [196]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor()
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

In [197]:
mse = mean_squared_error(y_test, rf_pred)
print("Random Forest Mean Squared Error:", mse)
rmse = np.sqrt(mse)
print("Random Forest Root Mean Squared Error:", rmse)
r2 = r2_score(y_test, rf_pred)
print("Random Forest R^2 Score:", r2)

Random Forest Mean Squared Error: 221.3605083333333
Random Forest Root Mean Squared Error: 14.878189013899956
Random Forest R^2 Score: -0.8291784727760851

In [198]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(PolynomialFeatures(2), LinearRegression())

pipeline.fit(X_train, y_train)
poly_pred = pipeline.predict(X_test)
mse = mean_squared_error(y_test, poly_pred)
print("Polynomial Regression Mean Squared Error:", mse)
rmse = np.sqrt(mse)
print(f"Mean error: {rmse:3.3} ({rmse/np.mean(poly_pred)*100:3.3}%)")
r2 = r2_score(y_test, poly_pred)
print("Polynomial Regression R^2 Score:", r2)

Polynomial Regression Mean Squared Error: 1365.8729374070942
Mean error: 37.0 (45.6%)
Polynomial Regression R^2 Score: -15.85872544889115